---
title: Progress Report
author: Naomi Carrigg and Marjorie Tidwell
date: November 16, 2023
output: 
  html_document:
    theme: cerulean

    embed-resources: true
---

# Admin
- Title: Air Quality in DC
- Group Members: Naomi Carrigg (413) and Marjorie Tidwell (613)

# Topic and Data
- We settled on using the Air Quality History data set over the Emissions data set. This set has far more data points, longitude and latitude are provided, and the variables are of greater interest to our app.
- Given feedback from our project plan, we have decided to incorporate Census Data to analyze pollution given race and income data. The Census Data from the Bicentennial survey in 2020 has longitudinal and latitudinal data, making it easy to join with the Air Quality data set.
- Using this data set, we can look at the variety of pollutants that are tracked, including PM2.5, nitrogen dioxide, ozone, and sulfur dioxide. We will allow users to select the pollutant they want to visualize and see both relationships between that pollutant and other ones as well as a map of DC with the concentrations of pollutants.
- Data has been collected from Open Data DC and tidying has begun to focus on the variables needed for our study, including site_name, latitude, longitude, parameter name, and sample measurement

# Ethical Review
- By using Open Data DC we are ensuring that the data being used was collected ethically and preserves privacy.
- Similarly, the Census data is collected in an ethical way that represents a general selection of the population.

# App Design
- On the main tab, a univariate analysis will be provided where users can select a pollutant and see the concentration of that pollutant in DC. Users will select one variable from the air quality data.
- On the second tab, a multivariate analysis will be provided with a liner model and a map of DC. Users will select two variables, either from the air quality data or the census. So they can see if two pollutants have similar distributions in the city, or if a pollutant has any pattern with a demographic pattern.
- On a third tab, a logistic analysis will be shown with pollutants given multiple demographic variables, allowing users to see how intersectionality plays a role in pollution. Users will select any number of variabls from either data set to see a full picture of pollution and demographics.
- The main changes from the plan include using Census data and utilizing the tools learned from last class about interactive maps.

# Responsibilities

Shared Responsibilities
  * Data Cleaning 
  
  * Joining the two data sets and formatting with the correct ESPG
  
  * Overall visual cohesion of the app

Naomi (Finalized Responsibilities)

  * Business logic for simple linear regression
  * UI for simple linear regression
  * Server for simple linear regression
  * Static context for data set or pdf document with context
  * Tests for simple linear regression like T test
  * Static map for simple linear regression 

Margie (Finalized Responsibilities)

  * Business logic for multiple linear regression
  * UI for multiple linear regression
  * Server for multiple linear regression
  * Tests for multiple linear regression
  * Residual plots 
  * Logistic regression to allow binomial variables to be tested
  * Tests for multicollinearity including VIF 
  * Chi square test for two categorical variables
  * ANOVA test
  
# Risk Assessment

The greatest risk we face is that we are unable to properly combine the data sets and there fore would not be able to have data from the census.
I am confident that we will be able to find a way. However if we are unable to combine the data, we can still use the longitude and latitude
values from the air quality data to sort by ward and provide statistics factored by this variable that we would create.

I would say another big risk is that we have a lot of categorical variables and they will all need to be one hot encoded to be used. One hot encoded variables are difficult to deal with and this will be especially difficult since there are so many that need this transformation. One way that we could mitigate this risk is by reducing the number of categorical variables that we actually include. 

# Collaboration

November 17: Progress Report is written up and turned in

November 22: Data has been cleaned and combined

November 30: Initial draft of App check in and internal review

December 4: Revisions have been applied 

December 8: Code cuttof! App should be finalized

December 9:  show drafted Vignette  

December 11: Finalize vignette and practice demonstration  

December 13: Practice presentation in front of friends






